# Worksheet 00

Name:  Renming Zhang
UID: U97677301

### Topics

- course overview
- python review

### Course Overview

a) Why are you taking this course?

To familiar with pytorch / numpy / pandas

b) What are your academic and professional goals for this semester?

Get an A

c) Do you have previous Data Science experience? If so, please expand.

No

d) Data Science is a combination of programming, math (linear algebra and calculus), and statistics. Which of these three do you struggle with the most (you may pick more than one)?

Probably statistics.

The rest of this worksheet is optional. If you have prior Python experience, you are welcome to skip it HOWEVER I strongly encourage you to try out the questions marked as `challenging`.

### Python review (Optional)

#### Lambda functions

Python supports the creation of anonymous functions (i.e. functions that are not bound to a name) at runtime, using a construct called `lambda`. Instead of writing a named function as such:

In [ ]:
def f(x):
    return x**2
f(8)

64

One can write an anonymous function as such:

In [ ]:
(lambda x: x**2)(8)

64

A `lambda` function can take multiple arguments:

In [ ]:
(lambda x, y : x + y)(2, 3)

5

The arguments can be `lambda` functions themselves:

In [ ]:
(lambda x : x(3))(lambda y: 2 + y)

5

a) write a `lambda` function that takes three arguments `x, y, z` and returns `True` only if `x < y < z`.

In [1]:
(lambda x, y, z: x < y < z)(1,2,3)

True

b) write a `lambda` function that takes a parameter `n` and returns a lambda function that will multiply any input it receives by `n`.

In [2]:
lambda n: lambda x: n * x

#### Map

`map(func, s)`

`func` is a function and `s` is a sequence (e.g., a list).

`map()` returns an object that will apply function `func` to each of the elements of `s`.

For example if you want to multiply every element in a list by 2 you can write the following:

In [ ]:
mylist = [1, 2, 3, 4, 5]
mylist_mul_by_2 = map(lambda x : 2 * x, mylist)
print(list(mylist_mul_by_2))

[2, 4, 6, 8, 10]

`map` can also be applied to more than one list as long as they are the same size:

In [ ]:
a = [1, 2, 3, 4, 5]
b = [5, 4, 3, 2, 1]

a_plus_b = map(lambda x, y: x + y, a, b)
list(a_plus_b)

[6, 6, 6, 6, 6]

c) write a map that checks if elements are greater than zero

In [4]:
c = [-2, -1, 0, 1, 2]
gt_zero = map(lambda x:x>0,c)
list(gt_zero)

[False, False, False, True, True]

d) write a map that checks if elements are multiples of 3

In [5]:
d = [1, 3, 6, 11, 2]
mul_of3 = map(lambda x:x%3==0,d)
list(mul_of3)

[False, True, True, False, False]

#### Filter

`filter(function, list)` returns a new list containing all the elements of `list` for which `function()` evaluates to `True.`

e) write a filter that will only return even numbers in the list

In [6]:
e = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
evens = filter(lambda x:x%2==0,e)
list(evens)

[2, 4, 6, 8, 10]

#### Reduce

`reduce(function, sequence[, initial])` returns the result of sequencially applying the function to the sequence (starting at an initial state). You can think of reduce as consuming the sequence via the function.

For example, let's say we want to add all elements in a list. We could write the following:

In [8]:
from functools import reduce

nums = [1, 2, 3, 4, 5]
sum_nums = reduce(lambda acc, x : acc + x, nums, 0)
print(sum_nums)

15

Let's walk through the steps of `reduce` above:

1) the value of `acc` is set to 0 (our initial value)
2) Apply the lambda function on `acc` and the first element of the list: `acc` = `acc` + 1 = 1
3) `acc` = `acc` + 2 = 3
4) `acc` = `acc` + 3 = 6
5) `acc` = `acc` + 4 = 10
6) `acc` = `acc` + 5 = 15
7) return `acc`

`acc` is short for `accumulator`.

f) `*challenging` Using `reduce` write a function that returns the factorial of a number. (recall: N! (N factorial) = N * (N - 1) * (N - 2) * ... * 2 * 1)

In [11]:
factorial = lambda x : reduce(lambda a,b:a*b,range(1,x+1),1)
factorial(10)

3628800

g) `*challenging` Using `reduce` and `filter`, write a function that returns all the primes below a certain number

In [13]:
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

sieve = lambda x : reduce(lambda li, y: li + [y] if is_prime(y) else li,
        filter(lambda a: is_prime(a) and a < x, range(2, x+1)),
        [])
print(sieve(100))

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]

### What is going on?

This whole section is `*challenging`

For each of the following code snippets, explain why the output is what it is:

In [14]:
class Bank:
  def __init__(self, balance):
    self.balance = balance

  def is_overdrawn(self):
    return self.balance < 0

myBank = Bank(100)
if myBank.is_overdrawn :
  print("OVERDRAWN")
else:
  print("ALL GOOD")

OVERDRAWN

### Because the condition is not `the result of the function` but `the function itself`, which is always true.

In [ ]:
for i in range(4):
    print(i)
    i = 10

0
1
2
3

### After 10 has been assigned to `i`, `i` will go into iteration process, which will reset the value

In [ ]:
row = [""] * 3 # row i['', '', '']
board = [row] * 3
print(board) # [['', '', ''], ['', '', ''], ['', '', '']]
board[0][0] = "X"
print(board)

[['', '', ''], ['', '', ''], ['', '', '']]
[['X', '', ''], ['X', '', ''], ['X', '', '']]

### `board` is a list with three reference of `row`, you change one, you change them all.

In [1]:
funcs = []
results = []
for x in range(3):
    def some_func():
        return x
    funcs.append(some_func)
    results.append(some_func())  # note the function call here
funcs_results = [func() for func in funcs]
print(results) # [0,1,2]
print(funcs_results)

[<function some_func at 0x7aecb2d03eb0>, <function some_func at 0x7aecb2d3ca60>, <function some_func at 0x7aecb2d3c940>]
[0, 1, 2]
[2, 2, 2]

### Because the item in funcs are function, the loop variable was last assigned the value 2.

In [3]:
f = open("./data.txt", "w+")
f.write("1,2,3,4,5")
f.close()

nums = []
with open("./data.txt", "w+") as f:
  lines = f.readlines()
  for line in lines:
    nums += [int(x) for x in line.split(",")]

print(sum(nums))

0

### This file should be opened as read mode inorder to read the lines in it.